version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: permanent-cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install Heroku CLI
          command: sudo npm install -g heroku && heroku plugins:install heroku-builds
      - save_cache:
          key: permanent-cache
          paths:
            - ./.cache
            - ./public
            - /usr/local/lib/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
