version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.8
  slack: circleci/slack@1.0.0
jobs:
  build_and_deploy_staging:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-staging-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Build Static Site
          command: npm run build
      - run:
          name: Deploy Static Site to Staging
          command: HEROKU_APP_NAME=$HEROKU_APP_NAME_STAGING npm run deploy
      - slack/status:
          fail_only: 'true'
      - save_cache:
          key: dependency-cache-staging-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - public
  build_and_deploy_production:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-production-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Build Static Site
          command: npm run build
      - run:
          name: Deploy Static Site to Production
          command: HEROKU_APP_NAME=$HEROKU_APP_NAME_PRODUCTION npm run deploy
      - slack/status:
          fail_only: 'true'
      - save_cache:
          key: dependency-cache-production-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build_and_deploy_preview:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-preview-{{ checksum "preview/package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d preview/node_modules; then cd preview && npm install; fi
      - run:
          name: Deploy Preview
          command: cd preview && HEROKU_APP_NAME=$HEROKU_APP_NAME_PREVIEW npm run deploy
      - slack/status:
          fail_only: 'true'
      - save_cache:
          key: dependency-cache-preview-{{ checksum "preview/package.json" }}
          paths:
            - ./preview/node_modules
  push_production_and_preview:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Push latest commit to production branch
          command: git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/madetech/made-blog.git HEAD:production HEAD:preview
  smoke:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-smoke-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Run smoke tests
          command: npm run smoke
      - slack/status:
          fail_only: 'true'
      - save_cache:
          key: dependency-cache-smoke-{{ checksum "package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  master:
    jobs:
      - build_and_deploy_staging:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - build_and_deploy_staging
      - slack/approval-notification:
          message: https://staging.madetech.com is ready for review. Use workflow to deploy to production.
          requires:
            - build_and_deploy_staging
  smoke:
    jobs:
      - smoke
  production:
    jobs:
      - build_and_deploy_production:
          filters:
            branches:
              only:
                - production
  preview:
    jobs:
      - build_and_deploy_preview:
          filters:
            branches:
              only:
                - preview
