version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.3
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Build Static Site
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy_staging:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: public/{**/*.js,**/*.css,static/}
          to: 's3://$AWS_BUCKET_STAGING'
          arguments: |
            --acl public-read \
            --cache-control public,max-age=31536000,immutable \
            --delete
      - aws-s3/sync:
          from: public/**/*.html
          to: 's3://$AWS_BUCKET_PRODUCTION'
          arguments: |
            --acl public-read \
            --cache-control public,max-age=0,must-revalidate \
            --delete
            --acl public-read \
            --delete
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
