version: 2.1
orbs:
  slack: circleci/slack@2.5.0
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-build-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Run Test Suite
          command: npm test
      - run:
          name: Build Static Site
          command: BUILD_ID=${CIRCLE_BUILD_NUM} npm run build
      - run:
          name: Run Local Smoke Tests
          command: npm start & npm run smoke:local
      - slack/status:
          failure_message: ':red_circle: Failed to build ${CIRCLE_BRANCH}'
          fail_only: 'true'
          include_job_number_field: false
          include_project_field: false
      - save_cache:
          key: dependency-cache-build-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - public
  build_and_deploy_staging:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-staging-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Run Test Suite
          command: npm test
      - run:
          name: Build Static Site
          command: npm run build
      - run:
          name: Run Local Smoke Tests
          command: npm start & npm run smoke:local
      - run:
          name: Deploy Static Site to Staging
          command: BUILD_ID=${CIRCLE_BUILD_NUM} HEROKU_APP_NAME=${HEROKU_APP_NAME_STAGING} npm run deploy
      - run:
          name: Run Staging Smoke Tests
          command: BUILD_ID=${CIRCLE_BUILD_NUM} SMOKE_URL=${SITE_STAGING_URL} npm run smoke:build
      - slack/status:
          failure_message: ':red_circle: Failed to build and deploy ${SITE_STAGING_URL}'
          fail_only: 'true'
          include_job_number_field: false
          include_project_field: false
      - save_cache:
          key: dependency-cache-staging-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - public
  build_and_deploy_production:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-production-{{ checksum "package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d node_modules; then npm install; fi
      - run:
          name: Build Static Site
          command: npm run build
      - run:
          name: Deploy Static Site to Production
          command: BUILD_ID=${CIRCLE_BUILD_NUM} HEROKU_APP_NAME=${HEROKU_APP_NAME_PRODUCTION} npm run deploy
      - run:
          name: Run Production Smoke Tests
          command: BUILD_ID=${CIRCLE_BUILD_NUM} SMOKE_URL=${SITE_PRODUCTION_URL} npm run smoke:build
      - slack/status:
          success_message: ':tada: ${SITE_PRODUCTION_URL} has just been deployed.'
          failure_message: ':red_circle: Failed to build and deploy ${SITE_PRODUCTION_URL}'
          include_job_number_field: false
          include_project_field: false
      - save_cache:
          key: dependency-cache-production-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build_and_deploy_preview:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-preview-{{ checksum "preview/package.json" }}
      - run:
          name: Install NPM Dependencies
          command: if ! test -d preview/node_modules; then cd preview && npm install; fi
      - run:
          name: Deploy Preview
          command: cd preview && HEROKU_APP_NAME=${HEROKU_APP_NAME_PREVIEW} npm run deploy
      - slack/status:
          fail_only: 'true'
      - save_cache:
          key: dependency-cache-preview-{{ checksum "preview/package.json" }}
          paths:
            - ./preview/node_modules
  push_production_and_preview:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Push latest commit to production branch
          command: git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/madetech/site.git HEAD:production HEAD:preview
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - production
                - preview
  master:
    jobs:
      - build_and_deploy_staging:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - build_and_deploy_staging
      - slack/approval-notification:
          message: ':mag: ${SITE_STAGING_URL} is ready for review. Use workflow to deploy to production.'
          requires:
            - build_and_deploy_staging
      - push_production_and_preview:
          requires:
            - hold
  production:
    jobs:
      - build_and_deploy_production:
          filters:
            branches:
              only:
                - production
  preview:
    jobs:
      - build_and_deploy_preview:
          filters:
            branches:
              only:
                - preview
